network:
  balance_url: http://{}:{}/address/{}/balance
  block_path: [3ffeb28217261a2750e55f044202ab5e3ba5952ac34525babdfe0bad605c588e, 95d79ba70d1fa3143f2c7ac71b35f6539e34708f45777570e6215044f7f31a69]
  block_url: http://{}:{}/block/{}
  blocks_range_url: http://{}:{}/blocks/{}/{}
  blocks_url: http://{}:{}/blocks/{}
  client: None
  difficulty_adjustment_span: 500
  dns_seeds: []
  full_node_port: 30013
  halving_frequency: 210000
  initial_coins_per_block: 50
  max_transactions_per_block: 2000
  minimum_hash_difficulty: 4
  name: Cranky Coin
  nodes_url: http://{}:{}/nodes
  seed_nodes: !!set {10.0.2.15: null, 127.0.0.1: null, 127.0.0.2: null, 127.0.0.3: null,
    127.0.0.4: null, 137.198.12.80: null}
  significant_digits: 8
  status_url: http://{}:{}/status
  target_time_per_block: 600
  ticker_symbol: CRNK
  transaction_history_url: http://{}:{}/address/{}/transactions
  transactions_url: http://{}:{}/transactions
  version: 1
user: {block_path: null, encrypted_private_key: 8547fb7fa1253461d1e2069bb8f703f0bcd76353a917a4f39933ede8c92ac5349437,
  ip: 137.198.12.190, public_key: 0262efbea162c2cf367cfde91c40652dc658940534a638d880c3eed654f71bfcfd}
