network:
  balance_url: http://{}:{}/address/{}/balance
  block_path: None
  block_url: http://{}:{}/block/{}
  blocks_range_url: http://{}:{}/blocks/{}/{}
  blocks_url: http://{}:{}/blocks/{}
  client: None
  difficulty_adjustment_span: 500
  dns_seeds: []
  full_node_port: 30013
  halving_frequency: 210000
  initial_coins_per_block: 50
  max_transactions_per_block: 2000
  minimum_hash_difficulty: 4
  name: Cranky Coin
  nodes_url: http://{}:{}/nodes
  seed_nodes: [127.0.0.1, 127.0.0.2]
  significant_digits: 8
  status_url: http://{}:{}/status
  target_time_per_block: 600
  ticker_symbol: CRNK
  transaction_history_url: http://{}:{}/address/{}/transactions
  transactions_url: http://{}:{}/transactions
  version: 1
user: {block_path: null, encrypted_private_key: 930c9a7fcbbb3c2e75c629bca5c7789d57a9eb2469bc7bc08d5947a8e3626b85b4e7,
  ip: 137.198.12.190, public_key: 0241fed874533da466dffd968ce22ffe8c5701514e49decfb52971b704595cd260}
