network:
  balance_url: http://{}:{}/address/{}/balance
  block_url: http://{}:{}/block/{}
  blocks_range_url: http://{}:{}/blocks/{}/{}
  blocks_url: http://{}:{}/blocks/{}
  client: None
  difficulty_adjustment_span: 500
  dns_seeds: []
  full_node_port: 30013
  halving_frequency: 210000
  initial_coins_per_block: 50
  max_transactions_per_block: 2000
  minimum_hash_difficulty: 4
  name: Cranky Coin
  nodes_url: http://{}:{}/nodes
  seed_nodes: [127.0.0.1, 127.0.0.2]
  significant_digits: 8
  status_url: http://{}:{}/status
  target_time_per_block: 600
  ticker_symbol: CRNK
  transaction_history_url: http://{}:{}/address/{}/transactions
  transactions_url: http://{}:{}/transactions
  version: 1
user: {block_path: null, encrypted_private_key: c86d5f85a8bdf35b7af8983541de134ad327118fcc4415b439aa2d9d451c8b91a78ca7d46802717bb12cb06f14bbc6c66525765aa83db192f12f1d2d427607c8,
  ip: 127.0.0.1, public_key: 03921d3912da51563ec11361915ddfac6562822f2a456bcfb9a74cd040d6b257db}
