network:
  balance_url: http://{}:{}/address/{}/balance
  block_url: http://{}:{}/block/{}
  blocks_range_url: http://{}:{}/blocks/{}/{}
  blocks_url: http://{}:{}/blocks/{}
  client: None
  difficulty_adjustment_span: 500
  dns_seeds: []
  full_node_port: 30013
  halving_frequency: 210000
  initial_coins_per_block: 50
  max_transactions_per_block: 2000
  minimum_hash_difficulty: 4
  name: Cranky Coin
  nodes_url: http://{}:{}/nodes
  seed_nodes: [127.0.0.1, 127.0.0.2]
  significant_digits: 8
  status_url: http://{}:{}/status
  target_time_per_block: 600
  ticker_symbol: CRNK
  transaction_history_url: http://{}:{}/address/{}/transactions
  transactions_url: http://{}:{}/transactions
  version: 1
user: {block_path: null, encrypted_private_key: 88c6f05f004cdfa3d18e3bab7c199ffa21efd214db243c867de7cc58029e4556a9,
  ip: 127.0.0.1, public_key: 02c42c36d28ab784349a3d83d2c02552d88c2d4319ac80146a271670b5f28c0e48}
