network:
  balance_url: http://{}:{}/address/{}/balance
  block_path: [a406a7efcea5a7d4068d74e69e7bbe9fa5d33248b5697ef0b5fc7ee69b7b5e2a, b7b083fdfc91909531fd2a3a16f760f5ce5356b51e80f46783a5e5633f411823,
    66d6bd08c2f9cb69096f226157661f58c6ca6fc4b0c67bee514890240b3f1d83]
  block_url: http://{}:{}/block/{}
  blocks_range_url: http://{}:{}/blocks/{}/{}
  blocks_url: http://{}:{}/blocks/{}
  client: None
  difficulty_adjustment_span: 500
  dns_seeds: []
  full_node_port: 30013
  halving_frequency: 210000
  initial_coins_per_block: 50
  max_transactions_per_block: 2000
  minimum_hash_difficulty: 4
  name: Cranky Coin
  nodes_url: http://{}:{}/nodes
  seed_nodes: {127.0.0.1: null, 127.0.0.2: null, 127.0.0.3: null, 127.0.0.4: null}
  significant_digits: 8
  status_url: http://{}:{}/status
  target_time_per_block: 600
  ticker_symbol: CRNK
  transaction_history_url: http://{}:{}/address/{}/transactions
  transactions_url: http://{}:{}/transactions
  version: 1
user: {block_path: null, encrypted_private_key: 363b2b4e21633977315d879ef6028e67947eabd796be755633ad3b5e26f8ea2614fd,
  ip: 137.198.12.190, public_key: 03dcbe41c81b883811d09eb93c55ddbee24543709fcb813155a249595de8163b18}
